name: Release

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2
      - name: Prepare Environment
        run: |
            echo "Removing large packages"
            sudo apt-get remove -y '^dotnet-.*' aspnetcore-targeting-pack-6.0
            sudo apt-get remove -y '^llvm-.*'
            sudo apt-get remove -y 'php.*'
            sudo apt-get remove -y '^mongodb-.*'
            sudo apt-get remove -y '^mysql-.*'
            sudo apt-get remove -y azure-cli google-cloud-sdk google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri
            sudo apt-get autoremove -y
            sudo apt-get clean
            echo "Removing large directories"
            sudo rm -rf /usr/share/dotnet/
            sudo rm -rf /usr/local/graalvm/
            sudo rm -rf /usr/local/.ghcup/
            sudo rm -rf /usr/local/share/powershell
            sudo rm -rf /usr/local/share/chromium
            sudo rm -rf /usr/local/lib/node_modules
            df -h
            
            sudo apt-get install bison gcc make curl ninja-build -y
      - name: Install NDK
        run: |
          echo "y" | sdkmanager --install "ndk;21.4.7075529" --sdk_root=${ANDROID_SDK_ROOT} &> /dev/null
          echo "sdk.dir=${ANDROID_HOME}" >> local.properties
          echo "ndk.dir=${ANDROID_HOME}/ndk/21.4.7075529" >> local.properties
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
      - name: Chmod Gradle
        run: chmod +x gradlew
      - name: Build
        run: |
          export commit="${{ github.event.head_commit.message }}"
          export commit_author="${{ github.actor }}"
          export commit_sha="${{ github.sha }}"
          export run_num="${{ github.run_number }}"
          bash build.sh
      - name: Find
        run: find "/home" -type f -name "*.apk" -print
      - name: Upload Aritfact
        uses: actions/upload-artifact@v4
        with:
          name: release Unsigned APK
          path: ${{ github.workspace }}/TMessagesProj/build/outputs/apk
      - name: Upload Aritfact 2
        uses: actions/upload-artifact@v4
        with:
          name: release Unsigned APK 2 
          path: ${{ github.workspace }}/TMessagesProj/app/build/outputs/apk
      - name: Upload Aritfact 3
        uses: actions/upload-artifact@v4
        with:
          name: release Unsigned APK 3
          path: ${{ github.workspace }}/build/outputs/apk
